site_name: Road to DevSecOps
docs_dir: catatan
theme:
  name: material
nav:
  - Home: index.md
  - Linux is Fun:
      - Logrotate: linux-fun/logrotate.md
  - Containers:
      - Containers Security:
          - Insecure Docker Registry: containers/containers-sec/insecure-docker-registry.md